# -*- coding: utf-8 -*-
"""Untitled61.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bGZRpxmTfWdnxhOQ1UjHqsC3PktpMsbc
"""

<!DOCTYPE html>
<html>
<body>
    <h1>Hello!</h1>
    <p>This is a simple webpage.</p>
</body>
</html>